all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
- - 17
- - 18
- - 19
- - 20
- - 21
- - 22
- - 23
- - 24
- - 25
- - 26
- - 27
- - 28
- - 29
- - 30
- - 31
- - 32
- - 33
all_joints_names:
- lefthandtip
- lefthandbase
- leftwrist
- leftelbow
- leftshoulder
- leftscapula
- righthandtip
- righthandbase
- rightwrist
- rightelbow
- rightshoulder
- rightscapula
- rightfoottip
- rightfootbase
- rightankle
- rightknee
- righthip
- leftfoottip
- leftfootbase
- leftankle
- leftknee
- lefthip
- nosetip
- crown
- baseneck
- spine75
- spine50
- spine25
- coccix
- tail25
- tail50
- tail75
- tail100
- sternum
batch_size: 1
bottomheight: 400
crop: true
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_DogTrain2Dec10/DogTrain2_rckoepke95shuffle7.mat
dataset_type: imgaug
display_iters: 1000
global_scale: 0.8
init_weights: /root/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/mobilenet_v2_0.35_224.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
leftwidth: 400
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_DogTrain2Dec10/Documentation_data-DogTrain2_95shuffle7.pickle
min_input_size: 64
minsize: 100
mirror: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: mobilenet_v2_0.35
num_joints: 34
pos_dist_thresh: 17
project_path: /root/dog_training_NN/DogTrain2-rckoepke-2019-12-10
rightwidth: 400
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
topheight: 400
